name: exi_trading_monitor
description: Trading Monitor App für MT5 Kontostände
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0

flutter:
  uses-material-design: true